eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/ # ,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8183    # 3-5
spring:
  application:
    name: ncyp-company-biz
  datasource:
    primary:
      name: testdb0
      url: jdbc:mysql://127.0.0.1:3306/springboot
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      name: testdb1
      url : jdbc:mysql://127.0.0.1:3307/springboot2
      username: root
      password: 1993212
      driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#    primary:
#      name: keepalived
#      url: jdbc:mysql://127.0.0.1:3306/ncyp?characterEncoding=utf8&useSSL=false
#      username: root
#      password:
#      driver-class-name: com.mysql.jdbc.Driver
#    secondary:
#      name: db
#      url: jdbc:mysql://192.168.6.27:3306/ncyp?characterEncoding=utf8&useSSL=false
#      username: root
#      password: cy.test18
#      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 36000
#  session:
#    store-type: redis
  zipkin:
    base-url: http://localhost:8774
  sleuth:
    sampler:
      percentage: 1.0
#  cloud:
#    stream:
#      bindings:
#        output_channel:   #channelName
#          destination: mydest   #destination，或者可以认为是发布－订阅模型里面的topic
#          binder: rabbit1
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 127.0.0.1
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /hostName
#mybatis:
#  mapperLocations: classpath:mapping/*.xml
#  type-aliases-package: com.ceying.chx.biz.base.entity
#  config-location: classpath:config/mybatis-config.xml
## 当post /refresh方式刷新配置 时 ，会有个安全限制，关掉就可以了
management:
  security:
    enabled: false
