server:
  port: 8082
redisConfig:
  host: localhost
  password:
  port: 6379
  maxWaitMillis: 10000
  maxIdle: 20
  maxTotal: 500
  numTestsPerEvictionRun: 3
  testOnBorrow: true
  testOnReturn: true
  testWhileIdle: true