eureka:
  client:
    healthcheck:    # eureka添加健康检查
        enabled: false
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 8183

spring:
  application:
    name: ncyp-bank-front
  redis:
      host: localhost
      port: 6379
      timeout: 36000
  session:
    store-type: redis
  aop:
    auto: true
    proxy-target-class: true