eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/  # ,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8186   # 6-8
spring:
  application:
    name: my-client # ncyp-company-triagreement
  datasource:

    url: jdbc:mysql://192.168.6.253:3306/ncyp?characterEncoding=utf8&useSSL=false
    username: root
    password: manage
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 36000
  session:
    store-type: redis
#  cloud:
#    config:
#      uri:  http://localhost:8768
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.ceying.chx.common.dto,com.ceying.chx.common.dao,com.ceying.chx.common.entity
management:
  security:
    enabled: false
