
server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto:  none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user   #全部小写    服务的名称
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder : trace
    org.hibernate.type.descriptor.sql.BasicExtractor : trace
    com.zhang : debug

eureka:
  client:
    healthcheck:    # eureka添加健康检查
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:               ## 自定义元数据
      zone: ABC
      deleizhang: BBC


