package com.ceying.chx.common.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 功能说明: 系统登录用户实体类
 *          <p>tsys_user_login</p><br>
 * 系统版本: 1.0 <br>
 * 开发人员: zhangdl
 * 开发时间: 2018/1/13 11:13<br>
 */
public class SysUserLoginDto implements Serializable {
	
	private static final long serialVersionUID = 9130814669895224030L;


    public
    String getTableName() {
        return "tsys_user_login";
    }

    /** QA:用户代码，外键TSYS_USER.USER_ID */
    private String userId;

    private Integer tenantId;

    /** 上次成功登录日 */
    private Date lastLoginDate;

    /** 最近登录操作IP */
    private String lastLoginIp;

    /** 登录累计失败次数 */
    private Integer loginFailTimes;

    /** 最后登录失败日 */
    private Date lastFailDate;

    /** 扩展字段 */
    private String extField;

    /** 组织ID */
    private String orgId;

    /** 用户名称 */
    private String userName;

    /** 用户中文简称 */
    private String tenantCnshortname;

    /** 用户英文代码 */
    private String tenantShortname;

    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.USER_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.USER_ID
     *
     * @param userId the value for ATSCLOUD.TSYS_USER_LOGIN.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_ID
     *
     * @param tenantId the value for ATSCLOUD.TSYS_USER_LOGIN.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_DATE
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_IP
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_IP
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for ATSCLOUD.TSYS_USER_LOGIN.LAST_LOGIN_IP
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LOGIN_FAIL_TIMES
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.LOGIN_FAIL_TIMES
     *
     * @mbggenerated
     */
    public Integer getLoginFailTimes() {
        return loginFailTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LOGIN_FAIL_TIMES
     *
     * @param loginFailTimes the value for ATSCLOUD.TSYS_USER_LOGIN.LOGIN_FAIL_TIMES
     *
     * @mbggenerated
     */
    public void setLoginFailTimes(Integer loginFailTimes) {
        this.loginFailTimes = loginFailTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_FAIL_DATE
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.LAST_FAIL_DATE
     *
     * @mbggenerated
     */
    public Date getLastFailDate() {
        return lastFailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.LAST_FAIL_DATE
     *
     * @param lastFailDate the value for ATSCLOUD.TSYS_USER_LOGIN.LAST_FAIL_DATE
     *
     * @mbggenerated
     */
    public void setLastFailDate(Date lastFailDate) {
        this.lastFailDate = lastFailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.EXT_FIELD
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.EXT_FIELD
     *
     * @mbggenerated
     */
    public String getExtField() {
        return extField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.EXT_FIELD
     *
     * @param extField the value for ATSCLOUD.TSYS_USER_LOGIN.EXT_FIELD
     *
     * @mbggenerated
     */
    public void setExtField(String extField) {
        this.extField = extField == null ? null : extField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.ORG_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.ORG_ID
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.ORG_ID
     *
     * @param orgId the value for ATSCLOUD.TSYS_USER_LOGIN.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.USER_NAME
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.USER_NAME
     *
     * @param userName the value for ATSCLOUD.TSYS_USER_LOGIN.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_CNSHORTNAME
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.TENANT_CNSHORTNAME
     *
     * @mbggenerated
     */
    public String getTenantCnshortname() {
        return tenantCnshortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_CNSHORTNAME
     *
     * @param tenantCnshortname the value for ATSCLOUD.TSYS_USER_LOGIN.TENANT_CNSHORTNAME
     *
     * @mbggenerated
     */
    public void setTenantCnshortname(String tenantCnshortname) {
        this.tenantCnshortname = tenantCnshortname == null ? null : tenantCnshortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_SHORTNAME
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.TENANT_SHORTNAME
     *
     * @mbggenerated
     */
    public String getTenantShortname() {
        return tenantShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.TENANT_SHORTNAME
     *
     * @param tenantShortname the value for ATSCLOUD.TSYS_USER_LOGIN.TENANT_SHORTNAME
     *
     * @mbggenerated
     */
    public void setTenantShortname(String tenantShortname) {
        this.tenantShortname = tenantShortname == null ? null : tenantShortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER_LOGIN.MOBILE
     *
     * @return the value of ATSCLOUD.TSYS_USER_LOGIN.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER_LOGIN.MOBILE
     *
     * @param mobile the value for ATSCLOUD.TSYS_USER_LOGIN.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
}