eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/  # ,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8186   # 6-8
spring:
  application:
    name: ncyp-company-triagreement #my-client # ncyp-company-triagreement
  datasource:

    url: jdbc:mysql://47.104.87.10:3306/ncyp?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.104.87.10
    port: 6379
    timeout: 36000
  session:
    store-type: redis
  zipkin:
    base-url: http://localhost:8774
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    stream:
      bindings:
        input:
          destination: mydest

      kafka:
        binder:
          zkNodes: 127.0.0.1
          brokers: 127.0.0.1
          input:
            consumer:
              resetOffsets: true

mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.ceying.chx.common.dto,com.ceying.chx.common.dao,com.ceying.chx.common.entity
## 当post /refresh方式刷新配置 时 ，会有个安全限制，关掉就可以了
management:
  security:
    enabled: false


