eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/ # ,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8768   # 8-0
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/JerryZDL/spring-cloud-config.git