#spring:
#  application:
#    name: EUREKA-HA
---
spring:
  application:
    name: EUREKA-HA
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
server:
  port: 8761

---
spring:
  application:
    name: EUREKA-HA
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762