drop table user if EXISTS ;
CREATE TABLE user (
                    id bigint generated by default as identity,
                    username VARCHAR (40),
                    name VARCHAR (20),
                    age int (3),
                    balance decimal(10,2),
                    PRIMARY KEY (id)
                    );