
server:
  port: 8182
spring:
  application:
    name: ncyp-bank-biz
  datasource:
    url: jdbc:mysql://192.168.6.253:3306/ncyp?characterEncoding=utf8&useSSL=false #jdbc:mysql://127.0.0.1:3307/boss?characterEncoding=utf8&useSSL=false #jdbc:mysql://192.168.6.253:3306/ncyp?characterEncoding=utf8&useSSL=false
    username: root
    password:  manage #1993212 #manage
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 36000
  session:
    store-type: redis
  aop:
    auto: true
    proxy-target-class: true
#  cache:
#    ehcache:
#      config: ehcache.xml
#      provider: net.sf.ehcache.CacheManager
#    type: ehcache


eureka:
  client:
    healthcheck:    # eureka添加健康检查
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.ceying.chx.common.dto,com.ceying.chx.common.entity #批量增设别名
  config-location: classpath:config/mybatis-config.xml
mapper:
  mappers: com.ceying.chx.common.util.MyMapper
  not-empty: false
  identity: MYSQL

#mappers 多个接口时逗号隔开
#mapper.mappers=com.lf.util.MyMapper
#mapper.not-empty=false
#mapper.identity=MYSQL
