package com.ceying.chx.common.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysRoleDto implements Serializable {
	private static final long serialVersionUID = 4182048127576202215L;

	private String roleCode;

    private String roleName;

    private BigDecimal tenantId;

    private String creator;

    private String remark;

    private String parentId;

    private String rolePath;

    private BigDecimal roleOrder;

    private Date createDate;

    private Date modifyDate;

    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_CODE
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_CODE
     *
     * @param roleCode the value for ATSCLOUD.TSYS_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_NAME
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for ATSCLOUD.TSYS_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.TENANT_ID
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.TENANT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.TENANT_ID
     *
     * @param tenantId the value for ATSCLOUD.TSYS_ROLE.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(BigDecimal tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.CREATOR
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.CREATOR
     *
     * @param creator the value for ATSCLOUD.TSYS_ROLE.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.REMARK
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.REMARK
     *
     * @param remark the value for ATSCLOUD.TSYS_ROLE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.PARENT_ID
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.PARENT_ID
     *
     * @param parentId the value for ATSCLOUD.TSYS_ROLE.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_PATH
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.ROLE_PATH
     *
     * @mbggenerated
     */
    public String getRolePath() {
        return rolePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_PATH
     *
     * @param rolePath the value for ATSCLOUD.TSYS_ROLE.ROLE_PATH
     *
     * @mbggenerated
     */
    public void setRolePath(String rolePath) {
        this.rolePath = rolePath == null ? null : rolePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_ORDER
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.ROLE_ORDER
     *
     * @mbggenerated
     */
    public BigDecimal getRoleOrder() {
        return roleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.ROLE_ORDER
     *
     * @param roleOrder the value for ATSCLOUD.TSYS_ROLE.ROLE_ORDER
     *
     * @mbggenerated
     */
    public void setRoleOrder(BigDecimal roleOrder) {
        this.roleOrder = roleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.CREATE_DATE
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.CREATE_DATE
     *
     * @param createDate the value for ATSCLOUD.TSYS_ROLE.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.MODIFY_DATE
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.MODIFY_DATE

     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.MODIFY_DATE
     *
     * @param modifyDate the value for ATSCLOUD.TSYS_ROLE.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_ROLE.ORG_ID
     *
     * @return the value of ATSCLOUD.TSYS_ROLE.ORG_ID
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_ROLE.ORG_ID
     *
     * @param orgId the value for ATSCLOUD.TSYS_ROLE.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }
}