package com.ceying.chx.common.dto;


import java.io.Serializable;
import java.util.Date;

public class SysUserDto implements Serializable {
	private static final long serialVersionUID = -5026728323973380085L;
    private int start;
    private int limit;
	/** 用户代码 */
    private String userId;

    private Integer tenantId;

    /** 用户名称 */
    private String userName;

    /** 用户密码 */
    private String userPwd;

    /** QA:组织ID,外键:TSYS_ORGANIZATION.ORG_ID */
    private String orgId;

    /** 取数据字典[SYS_BIZ_USER_CATE] 0-柜员 1-用户 */
    private String userType;

    /** 用于表示此用户状态 取数据字典[SYS_BIZ_USER_STATUS] 0-正常 1-注销 2-禁用 */
    private String userStatus;

    /** 用于表示此用户是否被锁定 取数据字典[SYS_BIZ_LOCK_STATUS] 0-签退 1-登录 2-非正常签退 3-锁定 */
    private String lockStatus;

    /** 创建时间 */
    private Date createDate;

    /** 最后修改时间 */
    private Date modifyDate;

    /** 密码修改时间 */
    private Date passModifyDate;

    /** 用户手机号 */
    private String mobile;

    /** 用户邮箱 */
    private String email;

    /** 扩展标识 */
    private String extFlag;

    /** 备注 */
    private String remark;

    /** 扩展字段1 */
    private String extField1;

    /** 扩展字段2 */
    private String extField2;

    /** 扩展字段3 */
    private String extField3;

    /** 扩展字段4 */
    private String extField4;

    /** 扩展字段5 */
    private String extField5;

    /** QA:用户指令 */
    private Integer userOrder;

    /** QA:身份证件类型 */
    private String cIdentitytype;

    /** QA:证件号码 */
    private String cIdentityno;

    /** QA:证书 */
    private String cCredentials;

    //组织编码
    private String orgCode;
    //组织名称
    private String orgName;
    //组织级别
    private String orgLevel;
    //是否分配
    private String isAllocate;
    //角色编码
    private String roleCode;
    //角色名称
    private String roleName;

    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgLevel() {
        return orgLevel;
    }

    public void setOrgLevel(String orgLevel) {
        this.orgLevel = orgLevel;
    }

    public String getIsAllocate() {
        return isAllocate;
    }

    public void setIsAllocate(String isAllocate) {
        this.isAllocate = isAllocate;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_ID
     *
     * @param userId the value for ATSCLOUD.TSYS_USER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.TENANT_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER.TENANT_ID
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.TENANT_ID
     *
     * @param tenantId the value for ATSCLOUD.TSYS_USER.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_NAME
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_NAME
     *
     * @param userName the value for ATSCLOUD.TSYS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_PWD
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_PWD
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_PWD
     *
     * @param userPwd the value for ATSCLOUD.TSYS_USER.USER_PWD
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.ORG_ID
     *
     * @return the value of ATSCLOUD.TSYS_USER.ORG_ID
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.ORG_ID
     *
     * @param orgId the value for ATSCLOUD.TSYS_USER.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_TYPE
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_TYPE
     *
     * @param userType the value for ATSCLOUD.TSYS_USER.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_STATUS
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_STATUS
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_STATUS
     *
     * @param userStatus the value for ATSCLOUD.TSYS_USER.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.LOCK_STATUS
     *
     * @return the value of ATSCLOUD.TSYS_USER.LOCK_STATUS
     *
     * @mbggenerated
     */
    public String getLockStatus() {
        return lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.LOCK_STATUS
     *
     * @param lockStatus the value for ATSCLOUD.TSYS_USER.LOCK_STATUS
     *
     * @mbggenerated
     */
    public void setLockStatus(String lockStatus) {
        this.lockStatus = lockStatus == null ? null : lockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.CREATE_DATE
     *
     * @return the value of ATSCLOUD.TSYS_USER.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.CREATE_DATE
     *
     * @param createDate the value for ATSCLOUD.TSYS_USER.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.MODIFY_DATE
     *
     * @return the value of ATSCLOUD.TSYS_USER.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.MODIFY_DATE
     *
     * @param modifyDate the value for ATSCLOUD.TSYS_USER.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.PASS_MODIFY_DATE
     *
     * @return the value of ATSCLOUD.TSYS_USER.PASS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getPassModifyDate() {
        return passModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.PASS_MODIFY_DATE
     *
     * @param passModifyDate the value for ATSCLOUD.TSYS_USER.PASS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setPassModifyDate(Date passModifyDate) {
        this.passModifyDate = passModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.MOBILE
     *
     * @return the value of ATSCLOUD.TSYS_USER.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.MOBILE
     *
     * @param mobile the value for ATSCLOUD.TSYS_USER.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EMAIL
     *
     * @return the value of ATSCLOUD.TSYS_USER.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EMAIL
     *
     * @param email the value for ATSCLOUD.TSYS_USER.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FLAG
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FLAG
     *
     * @mbggenerated
     */
    public String getExtFlag() {
        return extFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FLAG
     *
     * @param extFlag the value for ATSCLOUD.TSYS_USER.EXT_FLAG
     *
     * @mbggenerated
     */
    public void setExtFlag(String extFlag) {
        this.extFlag = extFlag == null ? null : extFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.REMARK
     *
     * @return the value of ATSCLOUD.TSYS_USER.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.REMARK
     *
     * @param remark the value for ATSCLOUD.TSYS_USER.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_1
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FIELD_1
     *
     * @mbggenerated
     */
    public String getExtField1() {
        return extField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_1
     *
     * @param extField1 the value for ATSCLOUD.TSYS_USER.EXT_FIELD_1
     *
     * @mbggenerated
     */
    public void setExtField1(String extField1) {
        this.extField1 = extField1 == null ? null : extField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_2
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FIELD_2
     *
     * @mbggenerated
     */
    public String getExtField2() {
        return extField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_2
     *
     * @param extField2 the value for ATSCLOUD.TSYS_USER.EXT_FIELD_2
     *
     * @mbggenerated
     */
    public void setExtField2(String extField2) {
        this.extField2 = extField2 == null ? null : extField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_3
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FIELD_3
     *
     * @mbggenerated
     */
    public String getExtField3() {
        return extField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_3
     *
     * @param extField3 the value for ATSCLOUD.TSYS_USER.EXT_FIELD_3
     *
     * @mbggenerated
     */
    public void setExtField3(String extField3) {
        this.extField3 = extField3 == null ? null : extField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_4
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FIELD_4
     *
     * @mbggenerated
     */
    public String getExtField4() {
        return extField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_4
     *
     * @param extField4 the value for ATSCLOUD.TSYS_USER.EXT_FIELD_4
     *
     * @mbggenerated
     */
    public void setExtField4(String extField4) {
        this.extField4 = extField4 == null ? null : extField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_5
     *
     * @return the value of ATSCLOUD.TSYS_USER.EXT_FIELD_5
     *
     * @mbggenerated
     */
    public String getExtField5() {
        return extField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.EXT_FIELD_5
     *
     * @param extField5 the value for ATSCLOUD.TSYS_USER.EXT_FIELD_5
     *
     * @mbggenerated
     */
    public void setExtField5(String extField5) {
        this.extField5 = extField5 == null ? null : extField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.USER_ORDER
     *
     * @return the value of ATSCLOUD.TSYS_USER.USER_ORDER
     *
     * @mbggenerated
     */
    public Integer getUserOrder() {
        return userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.USER_ORDER
     *
     * @param userOrder the value for ATSCLOUD.TSYS_USER.USER_ORDER
     *
     * @mbggenerated
     */
    public void setUserOrder(Integer userOrder) {
        this.userOrder = userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.C_IDENTITYTYPE
     *
     * @return the value of ATSCLOUD.TSYS_USER.C_IDENTITYTYPE
     *
     * @mbggenerated
     */
    public String getCIdentitytype() {
        return cIdentitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.C_IDENTITYTYPE
     *
     * @param cIdentitytype the value for ATSCLOUD.TSYS_USER.C_IDENTITYTYPE
     *
     * @mbggenerated
     */
    public void setCIdentitytype(String cIdentitytype) {
        this.cIdentitytype = cIdentitytype == null ? null : cIdentitytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.C_IDENTITYNO
     *
     * @return the value of ATSCLOUD.TSYS_USER.C_IDENTITYNO
     *
     * @mbggenerated
     */
    public String getCIdentityno() {
        return cIdentityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.C_IDENTITYNO
     *
     * @param cIdentityno the value for ATSCLOUD.TSYS_USER.C_IDENTITYNO
     *
     * @mbggenerated
     */
    public void setCIdentityno(String cIdentityno) {
        this.cIdentityno = cIdentityno == null ? null : cIdentityno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATSCLOUD.TSYS_USER.C_CREDENTIALS
     *
     * @return the value of ATSCLOUD.TSYS_USER.C_CREDENTIALS
     *
     * @mbggenerated
     */
    public String getCCredentials() {
        return cCredentials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATSCLOUD.TSYS_USER.C_CREDENTIALS
     *
     * @param cCredentials the value for ATSCLOUD.TSYS_USER.C_CREDENTIALS
     *
     * @mbggenerated
     */
    public void setCCredentials(String cCredentials) {
        this.cCredentials = cCredentials == null ? null : cCredentials.trim();
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }
}