server:
  port: 8181
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:    # eureka添加健康检查
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@${eureka.instance.hostname}:${server.port}/eureka/